name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
    # tags:
    #   - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/brokenhandsio/queues-dash:0.0.1 #${{ github.ref_name }}
    - name: Push Docker image
      run: docker push ghcr.io/brokenhandsio/queues-dash:0.0.1 #${{ github.ref_name }}
